### ISSUE TITLE
Authors using the same semantic code and css

### ISSUE THREAD

**Issue by discodavey** [elifesciences/pattern-library#1163]
# Description

All authors lists to be using the same HTML and CSS code as in articles. 

Example:
![Screenshot 2022-09-12 at 14 29 53](https://user-images.githubusercontent.com/745794/189669276-257d88cc-c120-4ab8-9053-33e173c731ea.png)

![Screenshot 2022-09-12 at 14 29 47](https://user-images.githubusercontent.com/745794/189667027-9166eb56-ccbf-4f95-980a-f52d02ebc836.png)

https://elifesciences.org/articles/76249

The authors in Hero Banner and Highlights as well as teasers need to be as in an article which are ordered lists.

Examples of which one's need changing are below:

![Screenshot 2022-09-12 at 14 35 48](https://user-images.githubusercontent.com/745794/189669339-e1cd4edc-f1cf-454a-bdbb-b331bcef0e12.png)
![Screenshot 2022-09-12 at 14 35 59](https://user-images.githubusercontent.com/745794/189669352-d8397f55-f326-4c51-8b87-d7d75bc065e2.png)

# Subtasks

- [ ] Change Hero Banner authors from author line class to ordered list as per author list in an article
- [ ] Change Highlights authors from author line class to ordered list as per author list in an article
- [ ] Change Teaser authors from teaser__secondary_info class to ordered list as per author list in an article
- [ ] Do any additional work in Patterns PHP if needed
- [ ] Do any additional work in Journal if needed

If anymore need to be added then put them above.

# Definition of Done

- [ ] When all author lists have been converted to ordered author lists as per list above.
- [ ] Merge into pattern library
- [ ] Merge into Patterns-php and any additional work
- [ ] Merge in Journal and any additional work

**Comment by discodavey** [comment]
@Maelplaine This would be for Endava but not urgent at the moment

**Comment by discodavey** [comment]
Wrong place for the ticket.. Please ignore
